version: '3.8'
services:
  app:
    image: ${REGISTRY}${REPOSITORY}:${TAG:-latest}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "php-fpm-healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - app-data:/app
volumes:
  app-data: {}
