---
- name: Set up Amazon Linux EC2 instance for Yii2 app
  hosts: all
  become: yes
  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - docker
          - nginx
          - git
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Check if Docker Swarm is initialized
      command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_state
      changed_when: false

    - name: Initialize Docker Swarm
      command: docker swarm init
      when: swarm_state.stdout != 'active'

    - name: Create NGINX conf.d directory
      file:
        path: /etc/nginx/conf.d
        state: directory

    - name: Copy NGINX config
      copy:
        src: ../nginx/nginx.conf
        dest: /etc/nginx/conf.d/yii2.conf
        mode: '0644'

    - name: Start and enable NGINX
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: Ensure app directory exists
      file:
        path: /opt/yii2-app
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /opt/yii2-app/docker-compose.yml
        mode: '0644'
